### ISSUE TITLE
Find completed task bug

### ISSUE THREAD

**Issue by zxybazh** [Orthocenter/todos#2]
After hide completed tasks I can't find the completed tasks back in any way

**Comment by Orthocenter** [comment]
@zxybazh Did you mean after you clicked the X mark on the right of a specific task, you cannot find the task again? Actually, the X mark represents removing the task rather than hiding it.

**Comment by zxybazh** [comment]
I mean not by clicking the X but click hide completed tasks then I can find it in the completed task view but not in all tasks view, that's weird.

**Comment by Orthocenter** [comment]
Sorry for my poor understanding.     
That's really weird.  Tasks in completed view are subset of the tasks which are showed in all tasks view.
I just inspected relating code again, nothing seems to be wrong.  I also tested under several environments, app runs correctly, although still has some appearance problem due to browser compatibility.
I need more details to solve this problem. Would you please tell me your environmental information so that I can test under that condition?

**Comment by zxybazh** [comment]
OK, I test it again and the bug just gone, maybe I was tapped by some black magic, thank you for your hard work :-)
